### ISSUE TITLE
Remove reference to userland bundle

### ISSUE THREAD

**Issue by FanchTheSystem** [libre-informatique/MediaBundle#4]
in file:
https://github.com/libre-informatique/MediaBundle/blob/master/src/Entity/File.php
`
use AppBundle\Entity\OuterExtension\LibrinfoMediaBundle\FileExtension;`

should not reference AppBundle, as it may or may not have another name.

(Name of App Bundle is a user choice)

**Comment by GlennCavarle** [comment]
Hi @FanchTheSystem,
Yes, it is an important issue I already mentioned and that we have to address soon.

**Comment by FanchTheSystem** [comment]
@libre-informatique/devs concerned

**Comment by FanchTheSystem** [comment]
Issue almost all libre informatique bundle
